from .main_category import MainCategory
from .websites_category import WebsitesCategory
from .phones_category import PhonesCategory
from .search_category import SearchCategory
from .schedule_category import ScheduleCategory
from .ai_category import AICategory
from .proxy_category import ProxyCategory
from .behavior_category import BehaviorCategory
from .security_category import SecurityCategory
from .performance_category import PerformanceCategory
from .stats_category import StatsCategory
from .general_category import GeneralCategory